FROM python:3.11-slim-bullseye

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt && \
    chmod +x /app/entrypoint.sh

EXPOSE 5000

ENV FLASK_ENV=development

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
