version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/app
     - alembic:/app/alembic
     - photos:/app/photos
    depends_on:
     - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
  db:
    image: mysql:5.7
    volumes:
     - db_data:/var/lib/mysql
    env_file:
     - .env
volumes:
    db_data: {}
    alembic: {}
    photos: {}