version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
     - "5000:5000"
    volumes:
     - .:/app
     - alembic:/app/alembic
     - photo:/app/photo
    depends_on:
     - db
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
     - db_data:/var/lib/mysql
    env_file:
     - .env
volumes:
    db_data: {}
    alembic: {}
    photo: {}