FROM python:3.11-slim-bullseye

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt && \
    chmod +x /app/entrypoint.sh && \
    chmod +x /app/init_db.py

EXPOSE 5000

CMD ["sh", "-c", "python init_db.py && python app.py"]
