FROM python:3.11-slim-bullseye

WORKDIR /app

COPY . /app


RUN pip install --no-cache-dir -r requirements.txt


RUN apt-get update && apt-get install -y default-mysql-client


EXPOSE 5000

ENV FLASK_ENV=development

RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
