"""2024-05-22 01:17

Revision ID: 0ebc1a17cec5
Revises: 7ede8a4330b5
Create Date: 2024-05-22 01:17:28.483227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebc1a17cec5'
down_revision: Union[str, None] = '7ede8a4330b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
