"""2024-05-22 01:16

Revision ID: 7ede8a4330b5
Revises: 6009b9f1eabf
Create Date: 2024-05-22 01:16:44.303807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ede8a4330b5'
down_revision: Union[str, None] = '6009b9f1eabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_profiles', 'user_gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('user_gender', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
